project_id = "bgbavxtjlbvgplozizxu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.material-recognition]
verify_jwt = false

[functions.ai-material-analysis]
verify_jwt = false

[functions.vector-similarity-search]
verify_jwt = false

[functions.voice-to-material]
verify_jwt = false

[functions.crewai-3d-generation]
verify_jwt = false