project_id = "bgbavxtjlbvgplozizxu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.material-recognition]
verify_jwt = false

[functions.ai-material-analysis]
verify_jwt = false

[functions.vector-similarity-search]
verify_jwt = false

[functions.voice-to-material]
verify_jwt = false

[functions.crewai-3d-generation]
verify_jwt = false

[functions.svbrdf-extractor]
verify_jwt = false

[functions.nerf-processor]
verify_jwt = false

[functions.enhanced-rag-search]
verify_jwt = false

[functions.huggingface-model-trainer]
verify_jwt = false

[functions.ocr-processing]
verify_jwt = false

[functions.spaceformer-analysis]
verify_jwt = false

[functions.rag-knowledge-search]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.style-analysis]
verify_jwt = false

[functions.material-properties-analysis]
verify_jwt = false

[functions.enhanced-crewai]
verify_jwt = false

[functions.material-scraper]
verify_jwt = false

[functions.convertapi-pdf-processor]
verify_jwt = false

[functions.parse-sitemap]
verify_jwt = false

[functions.scrape-single-page]
verify_jwt = false

[functions.scrape-session-manager]
verify_jwt = false